version: "3"
services:
  app:
    ports:
      - "8080:8080"
    command: bash -c 'sleep 3 && npm start'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./app:/app"
  caddy:
    image: caddy:2.4.5-alpine
    depends_on:
      - app
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app/:/srv
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    
    
