version: "3"
services:
  app:
    depends_on:
      - db
    image: prostoandrei/devops-for-programmers-project-lvl1
    build:
      context: .
      dockerfile: Dockerfile.production
    command: bash -c "npm ci && npm test"
    volumes:
      - "./app:/app"
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  db:
    image: postgres:14.3  
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    

