version: "3"
services:
  app:
    image: prostoandrei/devops-for-programmers-project-lvl1
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "8080:8080"
    command: npm test

