version: "3"
services:
  app:
    ports:
      - "8080:8080"
    command: npm run dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./app:/app"
  caddy:
    image: caddy:2.4.5-alpine
    depends_on:
      - app
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile"
    
    
